trigger:
- '*'

variables:
- group : Build
- name  : local.projectName
  value : 'dotnet.core'
- name  : local.artifact
  value : 'packages'
  
stages:
- stage: Test
  displayName: Testing
  jobs:
  - job: Unit_Testing
    displayName: Unit_Testing
    pool:
      vmImage: $(build.pool)
    workspace:
      clean: all
    variables:
    - group : Build.Unit_Test
    - name  : local.codecoveragehistory.directory
      value : '$(Build.ArtifactStagingDirectory)/history'
    - name  : local.codecoveragehistory.directory
      value : ${{ lower( variables['local.projectName']) }}.$(Build.SourceBranchName)
    - name  : 'disable.coverage.autogenerate'
      value : 'true'
    steps:
    # Preparing
    - task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
      displayName: Prepare Analysis on SonarCloud
      inputs:
        SonarCloud: SonarCloud
        organization: $(unit_test.sonarcloud.organization)
        projectKey: ${{ lower( variables['local.projectName']) }}
        projectName: ${{ lower( variables['local.projectName']) }}
        extraProperties: |
          sonar.coverage.exclusions=**/*[Uu]nit[Tt]ests*/**/*
          sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/**/coverage.opencover.xml

    - task: UniversalPackages@0
      displayName: Get Code Coverage History
      continueOnError: true
      inputs:
        command: download
        downloadDirectory: $(local.codecoveragehistory.directory)
        feedsToUse: internal
        vstsFeed: $(unit_test.coverage.history.feed)
        vstsFeedPackage: $(local.codecoveragehistory.directory)
        vstsPackageVersion: '0.*'

    # Building
    - task: DotNetCoreCLI@2
      displayName: Building   
      inputs:
        projects: '**/*.sln'    # The <ProjectGuid> element is not required if you build a solution (sln) containing that project.
                                # for SonarQube
        arguments: '--configuration $(build.configuration.release)'

    # Testing
    - task: DotNetCoreCLI@2
      displayName: Run Unit Tests
      inputs:
        command: test
        arguments: '--no-build --configuration $(build.configuration.release) /p:CollectCoverage=true /p:CoverletOutputFormat=\"cobertura,opencover\"'
        publishTestResults: true
        projects: '**/*[Tt]ests/*.csproj'

    # Coverage Report
    - task: Palmmedia.reportgenerator.reportgenerator-build-release-task.reportgenerator@4
      displayName: Generating Coverage Report
      inputs:
        reports: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml'
        targetdir: $(Build.SourcesDirectory)/Coverage
        reporttypes: HtmlInline_AzurePipelines;Cobertura;Badges
        historydir: $(local.codecoveragehistory.directory)

    - task: UniversalPackages@0
      displayName: Publish Code Coverage History
      inputs:
        command: publish
        publishDirectory: $(local.codecoveragehistory.directory)
        feedsToUsePublish: internal
        vstsFeedPublish: $(unit_test.coverage.history.feed)
        vstsFeedPackagePublish: $(local.codecoveragehistory.directory)
        versionOption: patch
        packagePublishDescription: Code Coverage History for repository $(Build.Repository.Name) on branch $(Build.SourceBranchName)
        verbosity: Information

    - task: PublishCodeCoverageResults@1
      displayName: Publish Code Coverage Report
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: $(Build.SourcesDirectory)/Coverage/Cobertura.xml
        reportDirectory: $(Build.SourcesDirectory)/Coverage

    # Code Analysis
    - task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
      displayName: Run Code Analysis

    - task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
      displayName: Publish Quality Gate Result

    - task: WhiteSource Bolt@20
      displayName: 'Run WhiteSource Bolt'
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')  # Free tier only allow 5 tests per repo per day, so only enable in master
  
- stage: Package
  displayName: Packaging
  dependsOn: Test
  condition: succeeded()
  jobs:
  - job: Package
    displayName: Packaging
    pool:
      vmImage: $(build.pool)
    workspace:
      clean: all
    variables:
    - group: Build.NuGet
    steps:      
    - task: DotNetCoreCLI@2
      displayName: Create Pre-release Package
      condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')
      inputs:
        command: pack
        buildProperties: $(nuget.prerelease.suffix)
        packDirectory: '$(Build.ArtifactStagingDirectory)/$(local.artifact)'
        arguments: '--configuration $(build.configuration.release)'

    - task: DotNetCoreCLI@2
      displayName: Create Release Package
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
      inputs:
        command: pack
        packDirectory: '$(Build.ArtifactStagingDirectory)/$(local.artifact)'
        arguments: '--configuration $(build.configuration.release)'
  
    - publish: $(Build.ArtifactStagingDirectory)/$(local.artifact)
      displayName: Publishing
      artifact: $(local.artifact)

- stage: Publish
  displayName: Publish
  dependsOn: Package
  condition: succeeded()
  jobs:
  - job: Publishing_Prerelease
    displayName: Publishing Prerelease     
    pool:
      vmImage: $(build.pool)
    workspace:
      clean: all
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')
    variables:
    - group: Build.NuGet
    steps:
    - checkout: none

    - download: current
      displayName: Download artifacts
      artifact: $(local.artifact)

    - task: NuGetCommand@2
      displayName: 'Pushing to Feed: $(nuget.artifact.feed.prerelease)'
      inputs:
        command: push
        packagesToPush: '$(Agent.BuildDirectory)/$(local.artifact)/*.nupkg'
        nuGetFeedType: internal
        publishVstsFeed: $(nuget.artifact.feed.prerelease)

  - job: Publishing_AzureDevops
    displayName: Publishing to Azure DevOps Feed  
    pool:
      vmImage: $(build.pool)
    workspace:
      clean: all
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    variables:
    - group: Build.NuGet
    steps:
    - checkout: none

    - download: current
      displayName: Download artifacts
      artifact: $(local.artifact)

    - task: NuGetCommand@2
      displayName: 'Pushing to Feed: $(nuget.artifact.feed.production)'
      inputs:
        command: push
        packagesToPush: '$(Agent.BuildDirectory)/$(local.artifact)/*.nupkg'
        nuGetFeedType: internal
        publishVstsFeed: $(nuget.artifact.feed.production)
        allowPackageConflicts: true

  - deployment:
    displayName: Publishing to NuGet.org
    pool:
      vmImage: $(build.pool)
    workspace:
      clean: all
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    variables:
    - group: Build.NuGet
    environment: NuGet-Repo
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: none

          - download: current
            displayName: Download artifacts
            artifact: $(local.artifact)

          - task: DotNetCoreCLI@2
            displayName: Pushing to NuGet.org
            inputs:
              command: custom
              custom: nuget
              arguments: 'push $(Agent.BuildDirectory)/$(local.artifact)/*.nupkg --source $(nuget.org.source) --api-key $(nuget.org.apiKey) --skip-duplicate'
